version: "3.9"

services:
  # springboot:
  #  image: springboot-docker-compose-app:1
  #  build:
  #    context: ./api
  #    dockerfile: Dockerfile
  #  volumes:
  #    - /data/springboot
  #  ports:
  #    - "8080:8080"
  db:
    container_name: db-restapiwithspringboot
    build: 
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"