version: "3.9"

services:
  # springboot:
  #  image: springboot-docker-compose-app:1
  #  build:
  #    context: ./api
  #    dockerfile: Dockerfile
  #  volumes:
  #    - /data/springboot
  #  ports:
  #    - "8080:8080"
  db:
    container_name: db-restapiwithspringboot
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"